language: java

jdk:
    - openjdk11

install:
  - if [ "$_system_name" == "OSX" ]; then S=macos; D=/Contents/Home/; else S=linux; D=/; fi
  - mkdir download
  - cd download
  - wget https://github.com/oracle/graal/releases/download/vm-1.0.0-rc14/graalvm-ce-1.0.0-rc14-$S-amd64.tar.gz
  - cd ..
  - tar fxz download/graalvm-ce-1.0.0-rc*-$S-amd64.tar.gz
  
script:
  - mvn clean install
  - ls -d graalvm*
  - JH=`ls -d graalvm*`$D
  - ls -l $JH
  - JAVA_HOME=$JH mvn clean install
matrix:
    include:
        - os: linux
